- name: Install Packages
  hosts: all
  become: yes

  vars:
    packages_to_install:
      - zip
      - unzip
      - jq
      - wget

  tasks:
    - name: Print installation progress
      debug:
        msg: "installing {{ item }}"
      loop: "{{ packages_to_install }}"
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Install utility packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"
      when: ansible_facts["distribution"] == "Ubuntu"
