- name: Show Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yaml

  tasks:
    - name: Show passwords
      debug:
        msg: "My password is {{ password }}"
  
    - name: Show api
      debug: 
        msg: "My api key is {{ api_key }}"
