#SPDX-License-Identifier: MIT-0
---
# tasks file for role/Docker

- name: update system
  apt:
    name: "*"
    state: latest

- name: INstall docker
  apt:
    name: docker.io
    state: latest

- name: add users to docker
  user:
     name: "{{ item }}"
     comment: pratik patil
     group: docker
     append: true
  # sudo usermod -aG docker ubuntu
   loop: "{{ docker_user }}"

- name: register docker version
  command: docker --version
  register: docker_version

- name: show docker version
  debug:
    msg: "{{ docker_version.stdout }}"

