#SPDX-License-Identifier: MIT-0
---
# tasks file for role/Docker

- name: update system
  apt:
    name: "*"
    state: latest

- name: INstall docker
  apt:
    name: docker.io
    state: latest

- name: add users to docker
  user:
    name: "{{ item }}"
    comment: pratik patil
    groups: docker
    append: true
  loop: "{{ docker_user }}"

- name: register docker version
  command: docker --version
  register: docker_version

- name: show docker version
  debug:
    msg: "{{ docker_version.stdout }}"

- name: show running container
  command: docker ps
